using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FourSoulsCore
{
    public enum CharacterNames
    {
        Isaac,
        Cain,
        Maggy,
        Judas,
        Samson,
        Eve,
        Lilith,
        BlueBaby,
        Lazarus,
        TheForgotten,
        Eden,
        TheLost,
        TheKeeper,
        Azazel,
        Apollyon,
        Guppy,
        BumBo,
        WhoreofBabylon,
        DarkJudas,
        Tapeworm,
        Albert,
        Bethany,
        JacobAndEsau,
        TheBroken,
        TheHoarder,
        TheDuantless,
        TheDeceiver,
        TheSavage,
        TheCurdled,
        TheHarlot,
        TheSoiled,
        TheEnigma,
        TheFettered,
        TheCapricious,
        TheBaleful,
        TheMiser,
        TheBenighted,
        TheEmpty,
        TheZealot,
        TheDeserter,
        Ash,
        GuySpelunky,
        TheSilent,
        CaptainViridian,
        TheKnight,
        PinkKnight,
        Boyfriend,
        PsychoGoreman,
        BlindJohnny,
        SaladFingers,
        BlueArcher,
        Quote,
        Crewmate,
        BumBoTheWeird,
        Steven,
        Johnny,
        Baba,
        Edmund,
        FlashIsaac,
    }
}
