# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Build (Tests)
      run: dotnet build --no-restore ./Test/Test.csproj
    - name: Add coverlet collector (Test)
      run: dotnet add Test/Test.csproj package coverlet.collector
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=cobertura ./Tests/Tests.csproj
    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        verbose: true
        files: InstrumentControl/Tests*/TestResults/*/coverage.cobertura.xml
    - name: Uploade coverage reports to Codecov
      run: curl -Os https://uploader.codecov.io/latest/windows/codecov
        chmod +x codecov
        ./codecov -t ${721cdbba-69cc-44d5-a2a7-96b581584f9b}
