# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build And Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: cd FourSoulsStatsTracker && dotnet restore
    - name: Build
      run: cd FourSoulsStatsTracker && dotnet build --no-restore
    - name: Build (Test)
      run: dotnet build ./Test/Test.csproj 
    - name: Add coverlet collector (Test)
      run: cd FourSoulsStatsTracker && dotnet add Test/Test.csproj package coverlet.collector
    - name: Test
      run: cd FourSoulsStatsTracker && dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=cobertura ./Test/Test.csproj
    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        verbose: true
        fail_ci_if_error: true
        files: FourSoulsStatsTracker/Test*/TestResults/*/coverage.cobertura.xml
